[package]
name = "rust_android"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.19.0"
rust = { path = "../rust"}

[lib]
name = "rust_android"
crate-type = ["staticlib", "cdylib"]
